Repository ManageIQ/manageiq-providers-ibm_cic, pull requests merged in 2022-02, with the labels that each got.

#4 Remove Hakiri
  README.md
Labels: cleanup, developer

#5 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ibm_cic.gemspec
Labels: developer, test

#6 Add Build History Graph to README.md
  README.md
Labels: developer, test

#7 Fix missing cinder_manager caused by association :class_name
  app/models/manageiq/providers/ibm_cic/cloud_manager.rb
Labels: bug, najdorf/yes?

#8 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
