Repository ManageIQ/manageiq-providers-ibm_cic, pull requests merged in 2022-10, with the labels that each got.

#21 Subclass Snapshot under IbmCic::CloudManager
  app/models/manageiq/providers/ibm_cic/cloud_manager.rb
  app/models/manageiq/providers/ibm_cic/cloud_manager/snapshot.rb
Labels: bug

#22 Upgrade workflows to actions/checkout@v3
  .github/workflows/ci.yaml
Labels: enhancement, test

#23 Add PlacementGroup subclass to IbmCic
  app/models/manageiq/providers/ibm_cic/cloud_manager.rb
  app/models/manageiq/providers/ibm_cic/cloud_manager/placement_group.rb
  spec/vcr_cassettes/manageiq/providers/ibm_cic/cloud_manager/refresher.yml
Labels: enhancement
